version: '3'

services:
  app_bazar:
    build: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://men_bazar:3306/mendez_bazar?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: admin
      DB_PASSWORD: admin
    restart: always
    depends_on:
      men_bazar:
          condition: service_healthy
  men_bazar:
    image: mysql:8.3.0 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: mendez_bazar
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10